wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.6
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722419877.0
    t:
      1:
      - 5
      - 35
      - 53
      - 55
      - 105
      2:
      - 5
      - 35
      - 53
      - 55
      - 105
      3:
      - 23
      4: 3.10.12
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
agent:
  desc: null
  value:
    learning_rate: 0.01
    discount_factor: 0.1
    max_episodes: 5000
    exploration_rate: 1.0
    min_exploration_rate: 1.0e-06
    exploration_decay_rate: 1.0e-05
    learning_rate_decay: 0.9999
    min_learning_rate: 1.0e-05
    checkpoint_interval: 100
    e_decay_function: 11
    logging_file: agent_log.txt
alpha:
  desc: null
  value: 0.1
