agent:
  hidden_units: 16
  learning_rate: 2.5e-4  # Default value used in the code
  max_episodes: 10
  discount_factor: 0.1  # Listed as 'gamma' in the code
  exploration_rate: 1.0
  min_exploration_rate: 0.00001
  exploration_decay_rate: 0.995
  entropy_coefficient: 0.01  # Listed as 'ent_coef' in the code
  value_coefficient: 0.5  # Listed as 'vf_coef' in the code
  max_grad_norm: 0.5
  gae_lambda: 0.95
  e_decay_function: 3
  total_timesteps: 500000  # Default value used in the code
  num_steps: 5  # Default value used in the code
  clip_range: 0.2  # Default value used in the code