agent:
  hidden_units: 16
  learning_rate: 0.001
  discount_factor: 0.1
  max_episodes: 1000
  exploration_rate: 1.0
  min_exploration_rate: 0.01
  exploration_decay_rate: 0.995
  batch_size: 16
  learning_rate_decay: 0.999
  e_decay_function: 3