agent:
  hidden_units: 16
  learning_rate: 0.001  # Default value used in the code
  max_episodes: 1000
  discount_factor: 0.1  # Listed as 'gamma' in the code
  exploration_rate: 1.0
  min_exploration_rate: 0.00001
  learning_rate_decay: 0.999
  softmax_temperature: 1.0
  exploration_decay_rate: 0.995
  ent_coef: 0.8  # Listed as 'ent_coef' in the code
  vf_coef: 0.05  # Listed as 'vf_coef' in the code
  e_decay_function: 3