agent:
  hidden_units: 16
  actor_learning_rate: 0.001
  critic_learning_rate: 0.01
  discount_factor: 0.1
  max_episodes: 400
  exploration_rate: 1.0
  min_exploration_rate: 0.01
  exploration_decay_rate: 0.995
  batch_size: 16
  actor_learning_rate_decay: 0.999
  critic_learning_rate_decay: 0.999
  min_actor_learning_rate: 0.00001
  min_critic_learning_rate: 0.00001
  entropy_coefficient: 0.01
  value_coefficient: 0.5
  max_grad_norm: 0.5
  gae_lambda: 0.95
  clip_range: 0.2
  softmax_temperature: 0.1
  e_decay_function: 3