n_trials: 30  # Number of trials for Optuna to run

parameters:
#  alpha:
#    type: categorical
#    values: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
  hidden_units:
    type: categorical
    values: [64, 128, 256]
#  learning_rate:
#    type: float
#    min: 0.000001
#    max: 0.0001
#    log: false
#  discount_factor:
#    type: categorical
#    values: [0.1]
#  max_episodes:
#    type: categorical
#    values: [1000]
  batch_size:
    type: categorical
    values: [32, 64, 128]
#  gae_lambda:
#    type: categorical
#    values: [0.95]
#  clip_param:
#    type: categorical
#    values: [0.2, 0.9, 0.5]
#  n_epochs:
#    type: categorical
#    values: [10]
#  value_loss_coef:
#    type: categorical
#    values: [0.5]
#  entropy_coef:
#    type: categorical
#    values: [0.01]