# sweep.yaml
method: grid
metric:
  name: cumulative_reward
  goal: maximize

parameters:
  alpha:
    values: [0.3]  # Keep alpha fixed as per your original config

  learning_rate:
    values: [1e-4, 3e-4, 1e-3]

  clip_range:
    values: [0.1, 0.2, 0.3]

  n_epochs:
    values: [5, 10]

  batch_size:
    values: [64, 128]

  gae_lambda:
    values: [0.9, 0.95]

  value_coefficient:
    values: [0.5, 1.0]

  entropy_coefficient:
    values: [0.01, 0.05]

  max_grad_norm:
    values: [0.5, 1.0]

  discount_factor:
    values: [0.99, 0.999]

  actor_hidden_units:
    values: [[64], [64, 64]]

  critic_hidden_units:
    values: [[64], [64, 64]]

  update_interval:
    values: [1024, 2048]