program: main.py
method: grid
metric:
  name: cumulative_reward
  goal: maximize
parameters:
  alpha:
    values: [0.3]
  hidden_units:
    values: [8, 16, 32, 64]
  num_layers:
    values: [8, 14, 20]
  learning_rate:
    values: [0.001, 0.0001]
  softmax_temperature:
    values: [0.1, 0.2, 0.3]


  # Add any other parameters specific to your agents here